### ISSUE TITLE
fbjs error on bundle

### ISSUE THREAD

**Issue by natew** [garth/material-components#1]
When trying to bundle material-components, I'm getting issues because `tap-event-plugin` is trying to include `fbjs`, which then gives this error when bundled with webpack:

```
throw new Error('The fbjs package should never be required without a full path');
```

I'm on npm v2.14.4. Guessing this is a webpack or tap-event issue, just wondering how this works for you?

**Comment by garth** [comment]
Strange, I've not seen that. The webpack setup that the demo project uses is working, maybe there will be some clues if you compare?

**Comment by natew** [comment]
Ah interesting.

After more investigation the problem is mine. When I `npm install --save material-components` it dumps a bunch into my package.json, including fbjs/react and all peerDependencies of all sub-components.

Working on an environment plugin that manages your npm bundle for you, but now I see that I can't just "read package.json and bundle it" because it seems the new npm installs peerDeps right into your package.json.

**Comment by garth** [comment]
Glad you solved it!

**Comment by wzup** [comment]
@natew, what was your solution? I have the same bug, I include fbjs in vendors chunk:

```
    entry: {
        'index': './assets/js/react/dev/App',
        'todo': './assets/js/todo',
        'todo2': './assets/js/react/dev/App2',
        'vendors': [
                'jquery',
                'react',
                'react-dom',
                'react-flip-move',
                'react-tap-event-plugin',
                'react-addons-css-transition-group',
                'fbjs',  // I include fbjs in vendors chunk
                'react-scrollbar',
                'material-ui',
                'rc-slider',
            ]
    },
```
