### ISSUE TITLE
Incorrectly configured context

### ISSUE THREAD

**Issue by dchambers** [garth/material-components#3]
Firstly, thanks so much for the making the material UI components available to Redux and Cerebral users :+1:  So far, I've been able to use `<Row>` and `<Column>`, but when I try to use `<Select>` I get this error:

```
input.js:44 Uncaught TypeError: Cannot read property 'secondaryColor' of undefined
```

This is happening because `this.context.componentStyle` is defined, but set to `undefined`. Is there something I'm meant to do so the context is correctly set up, or is the problem merely due to the fact that I'm not using either Redux or Cerebral yet and am only building static components at this point &mdash; [Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html) style?

**Comment by garth** [comment]
It sounds like you haven't setup the context, not all components (eg Row, Col) need it so they will work without.

Checkout the getting started page for info on how to setup your app: http://garth.github.io/material-components/#/gettingStarted

**Comment by dchambers** [comment]
Oops, 'Getting Started' guide! Right, good idea that :-)
