### ISSUE TITLE
Datepicker needs Localization

### ISSUE THREAD

**Issue by ogyr** [garth/material-components#4]
Hi, Thanks for this very nice UI library! 
It's been great so far, but when I needed the datepicker component, I did not find an option to localize it to german, eg. via globalize.js or moment.js.

Did I miss anything, or is that just not possible at the moment?
And are there plans to implement it in the near future? 

Thanks!

**Comment by garth** [comment]
The picker should take the dates and text directly from moment js. So if you load moment and your translations, then set the locale in moment it should work 

Though admittedly I didn't test this fully yet. My current app will also support Deutsch so I test it very soon.

**Comment by ogyr** [comment]
Cool, thanks!

**Comment by garth** [comment]
I've added local locale support to the calendar and date picker today which should be more flexible than using moment's global setting. If you look at the demo you can now select German from the globe menu and the components should update. http://garth.github.io/material-components/#/calendar

**Comment by ogyr** [comment]
Awesome thanks!
